using System;
using System.IO;
using Anatawa12.AvatarOptimizer.PatchApplier;
using NUnit.Framework;

namespace Anatawa12.AvatarOptimizer.Test.PatchApplier
{
    public class PatchInfoTest
    {
        [Test]
        public void PatchRegistry_SaveAndLoad()
        {
            var tempFile = Path.GetTempFileName();
            try
            {
                // Create a registry with patches
                var registry = new PatchRegistry();
                var patch1 = new PatchInfo("abc1234567890", "1.9.0-rc.10", "base123456")
                {
                    PullRequest = "https://github.com/test/pr/1",
                    AppliedAt = new DateTime(2024, 1, 1, 12, 0, 0, DateTimeKind.Utc)
                };
                var patch2 = new PatchInfo("def7890123456", "1.9.0-rc.10", "base123456")
                {
                    BasePatch = "abc1234567890",
                    AppliedAt = new DateTime(2024, 1, 2, 12, 0, 0, DateTimeKind.Utc)
                };
                
                registry.AddPatch(patch1);
                registry.AddPatch(patch2);
                
                // Save to temp file
                var content = BuildRegistryContent(registry);
                File.WriteAllText(tempFile, content);
                
                // Load from temp file  
                var loaded = LoadRegistryFromContent(content);
                
                // Verify
                Assert.AreEqual(2, loaded.Patches.Count);
                Assert.AreEqual("abc1234567890", loaded.Patches[0].CommitHash);
                Assert.AreEqual("1.9.0-rc.10", loaded.Patches[0].BaseVersion);
                Assert.AreEqual("base123456", loaded.Patches[0].BaseCommit);
                Assert.AreEqual("https://github.com/test/pr/1", loaded.Patches[0].PullRequest);
                
                Assert.AreEqual("def7890123456", loaded.Patches[1].CommitHash);
                Assert.AreEqual("abc1234567890", loaded.Patches[1].BasePatch);
            }
            finally
            {
                if (File.Exists(tempFile))
                    File.Delete(tempFile);
            }
        }

        [Test]
        public void PatchRegistry_CanApplyPatch_NoPrevious()
        {
            var registry = new PatchRegistry();
            var patch = new PatchInfo("abc123", "1.9.0", "base123");
            
            Assert.IsTrue(registry.CanApplyPatch(patch));
        }

        [Test]
        public void PatchRegistry_CanApplyPatch_Continuous()
        {
            var registry = new PatchRegistry();
            var patch1 = new PatchInfo("abc123", "1.9.0", "base123");
            registry.AddPatch(patch1);
            
            var patch2 = new PatchInfo("def456", "1.9.0", "base123")
            {
                BasePatch = "abc123"
            };
            
            Assert.IsTrue(registry.CanApplyPatch(patch2));
        }

        [Test]
        public void PatchRegistry_CanApplyPatch_NotContinuous()
        {
            var registry = new PatchRegistry();
            var patch1 = new PatchInfo("abc123", "1.9.0", "base123");
            registry.AddPatch(patch1);
            
            var patch2 = new PatchInfo("def456", "1.9.0", "base123")
            {
                BasePatch = "wrong123"
            };
            
            Assert.IsFalse(registry.CanApplyPatch(patch2));
        }

        [Test]
        public void PatchRegistry_GetVersionString_NoPatches()
        {
            var registry = new PatchRegistry();
            var version = registry.GetVersionString("1.9.0-rc.10");
            
            Assert.AreEqual("1.9.0-rc.10", version);
        }

        [Test]
        public void PatchRegistry_GetVersionString_WithPatch()
        {
            var registry = new PatchRegistry();
            var patch = new PatchInfo("abc1234567890def", "1.9.0-rc.10", "base123");
            registry.AddPatch(patch);
            
            var version = registry.GetVersionString("1.9.0-rc.10");
            
            Assert.AreEqual("1.9.0-rc.10+patch.abc123456", version);
        }

        // Helper methods to test without file I/O
        private string BuildRegistryContent(PatchRegistry registry)
        {
            var sb = new System.Text.StringBuilder();
            sb.AppendLine("# Avatar Optimizer Applied Patches");
            sb.AppendLine("# This file is automatically generated and should not be edited manually");
            sb.AppendLine();

            foreach (var patch in registry.Patches)
            {
                sb.AppendLine("- patch:");
                sb.AppendLine($"  commit: {patch.CommitHash}");
                sb.AppendLine($"  base-version: {patch.BaseVersion}");
                sb.AppendLine($"  base-commit: {patch.BaseCommit}");
                if (!string.IsNullOrEmpty(patch.BasePatch))
                    sb.AppendLine($"  base-patch: {patch.BasePatch}");
                if (!string.IsNullOrEmpty(patch.PullRequest))
                    sb.AppendLine($"  pull-request: {patch.PullRequest}");
                sb.AppendLine($"  applied-at: {patch.AppliedAt:O}");
            }

            return sb.ToString();
        }

        private PatchRegistry LoadRegistryFromContent(string content)
        {
            var registry = new PatchRegistry();
            var lines = content.Split('\n');
            PatchInfo currentPatch = null;

            foreach (var line in lines)
            {
                if (string.IsNullOrWhiteSpace(line) || line.TrimStart().StartsWith("#"))
                    continue;

                if (line.StartsWith("- patch:"))
                {
                    if (currentPatch != null)
                        typeof(PatchRegistry)
                            .GetMethod("AddPatch")
                            .Invoke(registry, new object[] { currentPatch });
                    currentPatch = null;
                }
                else if (line.StartsWith("  commit: "))
                {
                    var commitHash = line.Substring("  commit: ".Length).Trim();
                    if (currentPatch == null && !string.IsNullOrEmpty(commitHash))
                    {
                        currentPatch = new PatchInfo(commitHash, "", "");
                    }
                }
                else if (currentPatch != null)
                {
                    if (line.StartsWith("  base-version: "))
                        currentPatch.BaseVersion = line.Substring("  base-version: ".Length).Trim();
                    else if (line.StartsWith("  base-commit: "))
                        currentPatch.BaseCommit = line.Substring("  base-commit: ".Length).Trim();
                    else if (line.StartsWith("  base-patch: "))
                        currentPatch.BasePatch = line.Substring("  base-patch: ".Length).Trim();
                    else if (line.StartsWith("  pull-request: "))
                        currentPatch.PullRequest = line.Substring("  pull-request: ".Length).Trim();
                    else if (line.StartsWith("  applied-at: "))
                    {
                        if (DateTime.TryParse(line.Substring("  applied-at: ".Length).Trim(), out var appliedAt))
                            currentPatch.AppliedAt = appliedAt;
                    }
                }
            }

            if (currentPatch != null)
                registry.AddPatch(currentPatch);

            return registry;
        }
    }
}
