
const AAO_VRCSDK3_AVATARS = "AAO_VRCSDK3_AVATARS"; 
function conditional(flag: string, inner: () => void) {
    console.log(`#if ${flag}`)
    inner();
    console.log(`#endif`)
}

function generate(type: string) {
    console.log(`    [Serializable]`)
    console.log(`    public class ${type}Set : PrefabSafeSet<${type}, ${type}Set.Layer>`)
    console.log(`    {`)
    console.log(`        public ${type}Set(Object outerObject) : base(outerObject)`)
    console.log(`        {`)
    console.log(`        }`)
    console.log(`        [Serializable]`)
    console.log(`        public class Layer : PrefabLayer<${type}>{}`)
    console.log(`    }`)
}

console.log("// generated by generate.ts")
console.log("// running generate.ts via deno will output this file.")
console.log(`using System;`)
console.log(`using System.Collections.Generic;`)
console.log(`using System.Reflection;`)
console.log(`using JetBrains.Annotations;`)
console.log(`using UnityEngine;`)
conditional(AAO_VRCSDK3_AVATARS, () => {
    console.log(`using VRC.Dynamics;`)
});
console.log(`using Object = UnityEngine.Object;`)
console.log(``)
console.log(`namespace Anatawa12.AvatarOptimizer.PrefabSafeSet`)
console.log(`{`)
generate("SkinnedMeshRenderer")
generate("MeshRenderer")
generate("Material")
generate("String")
conditional(AAO_VRCSDK3_AVATARS, () => {
    generate("VRCPhysBoneBase")
});
generate("Transform")
console.log(`}`)
