baseURL = 'https://vpm.anatawa12.com/avatar-optimizer/beta'
languageCode = 'en-us'
title = 'Avatar Optimizer (SNAPSHOT)'
theme = 'hugo-book'
defaultContentLanguage = 'en'
defaultContentLanguageInSubdir = true

[languages.en]
weight = 1
languageName = 'English'
[languages.en.params]
howToInstall = 'How to Install'

[languages.ja]
weight = 1
languageName = '日本語'
[languages.ja.params]
howToInstall = 'インストール方法'

[markup.goldmark.renderer]
unsafe = true

[params]
BookTheme = 'auto'
BookRepo = 'https://github.com/anatawa12/AvatarOptimizer'
BookEditPath = 'edit/master/.docs'

# OGP settings
title = 'Avatar Optimizer Official Docs'
