// generated by generate.ts
// running generate.ts via deno will output this file.
using System;
using System.Collections.Generic;
using System.Reflection;
using JetBrains.Annotations;
using UnityEngine;
using Object = UnityEngine.Object;

namespace Anatawa12.AvatarOptimizer.PrefabSafeSet
{
    [Serializable]
    internal class SkinnedMeshRendererSet : PrefabSafeSet<SkinnedMeshRenderer, SkinnedMeshRendererSet.Layer>
    {
        public SkinnedMeshRendererSet(Object outerObject) : base(outerObject)
        {
        }
        [Serializable]
        public class Layer : PrefabLayer<SkinnedMeshRenderer>{}
    }
    [Serializable]
    internal class MeshRendererSet : PrefabSafeSet<MeshRenderer, MeshRendererSet.Layer>
    {
        public MeshRendererSet(Object outerObject) : base(outerObject)
        {
        }
        [Serializable]
        public class Layer : PrefabLayer<MeshRenderer>{}
    }
    [Serializable]
    internal class MaterialSet : PrefabSafeSet<Material, MaterialSet.Layer>
    {
        public MaterialSet(Object outerObject) : base(outerObject)
        {
        }
        [Serializable]
        public class Layer : PrefabLayer<Material>{}
    }
    [Serializable]
    internal class StringSet : PrefabSafeSet<String, StringSet.Layer>
    {
        public StringSet(Object outerObject) : base(outerObject)
        {
        }
        [Serializable]
        public class Layer : PrefabLayer<String>{}
    }
}
