name: GameCI
# note: name is referenced by other workflow

on:
  push:
    branches: [ master, master-*, workflow-tests/* ]
  pull_request_target: {}
  workflow_dispatch: {}

permissions:
  contents: read
jobs:
  build-and-test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        unity:
          - 2022.3.22f1
    steps:
      # install tools
      - uses: anatawa12/sh-actions/setup-vrc-get@master

      # prepare project
      - name: Create Project directory
        shell: bash
        env: 
          UNITY_VERSION: ${{ matrix.unity }}
          unityVersion: ${{ matrix.unityVersion }}
        run: |-
          mkdir -p Assets Packages ProjectSettings
          echo "m_EditorVersion: $UNITY_VERSION" > ProjectSettings/ProjectVersion.txt
          # create manifest.json with necessary dependencies
          # com.vrchat.base has missing dependency to com.unity.modules.video
          # com.unity.xr.oculus, a package referenced by com.vrchat.base, has missing dependency to com.unity.modules.androidjni
          # NDMF had missing dependency to com.unity.modules.animation until https://github.com/bdunderscore/ndmf/pull/655 was merged in 1.8.0
          # We need com.unity.test-framework and com.unity.testtools.codecoverage for tests
          cat <<EOF > Packages/manifest.json
          {
            "dependencies": {
              "com.unity.modules.androidjni": "1.0.0",
              "com.unity.modules.animation": "1.0.0",
              "com.unity.modules.video": "1.0.0",
              "com.unity.test-framework": "1.3.7",
              "com.unity.testtools.codecoverage": "1.2.7"
            }
          }
          EOF
          # link tests
          ln -s "../Packages/com.anatawa12.avatar-optimizer/Test~" Assets/Test

      # prepare packages
      - uses: actions/checkout@v4
        with:
          path: Packages/com.anatawa12.avatar-optimizer
          ref: ${{ github.event.pull_request.head.sha }}
          persist-credentials: false
          allow-unsafe-pr-checkout: true
      - run: vrc-get install -y com.vrchat.avatars
      - uses: anatawa12/sh-actions/resolve-vpm-packages@master
        with:
          repos: |
            https://vpm.anatawa12.com/vpm.json
            https://vpm.nadena.dev/vpm-prerelease.json

      - uses: actions/cache@v4
        if: ${{ github.event_name != 'pull_request_target' || github.event.pull_request.head.repo.full_name == github.repository }}
        with:
          path: Library
          key: Library-${{ matrix.unity }}
          restore-keys: Library-${{ matrix.unity }}

      - uses: game-ci/unity-test-runner@v3
        id: gameci
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE_V3 }}
        with:
          testMode: EditMode
          coverageOptions: generateAdditionalMetrics;generateHtmlReport;generateBadgeReport;assemblyFilters:+com.anatawa12.avatar-optimizer.*,-*.test.*
          customParameters: 
          checkName: Test results ${{ matrix.unity }}

      - name: "Show files at root folder to find crash log"
        if: always()
        run: ls -la

      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: Test results ${{ matrix.unity }}
          path: ${{ steps.gameci.outputs.artifactsPath }}
      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: Coverage results ${{ matrix.unity }}
          path: ${{ steps.gameci.outputs.coveragePath }}

  conclude-gameci:
    runs-on: ubuntu-latest
    if: ${{ always() }}
    needs: [build-and-test]
    steps:
      - name: Conclude Tests
        env: { NEEDS: "${{ toJSON(needs) }}" }
        run: |
          echo "$NEEDS" | jq -c '. | to_entries[] | [.key, .value.result]'
          echo "$NEEDS" | jq -e '. | all(.result == "success")' > /dev/null
