name: GameCI Reports

on:
  workflow_run:
    workflows: ['GameCI']
    types:
      - completed

jobs:
  build-and-test:
    runs-on: ubuntu-slim
    permissions:
      contents: read
      actions: read
      checks: write
    steps:
      - uses: dorny/test-reporter@v3
        with:
          reporter: dotnet-nunit
          artifact: /Test results (.*)/
          name: 'Test report $1'
          fail-on-empty: false
          use-actions-summary: false # create checks
          path: '*.xml'
